// <auto-generated />
using System;
using ItlaincenstmentApp.Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ItlaincenstmentApp.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(InvestmentAppContext))]
    partial class InvestmentAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ItlaincenstmentApp.Core.Domain.Entities.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("Remove")
                        .HasColumnType("bit");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("AssetTypeId");

                    b.ToTable("Assets", (string)null);
                });

            modelBuilder.Entity("ItlaincenstmentApp.Core.Domain.Entities.AssetHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<DateTime>("HistoryValueDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Value")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasDefaultValue(0m);

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.ToTable("AssetHistorys", (string)null);
                });

            modelBuilder.Entity("ItlaincenstmentApp.Core.Domain.Entities.AssetType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("Remove")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("AssetTypes", (string)null);
                });

            modelBuilder.Entity("ItlaincenstmentApp.Core.Domain.Entities.InvestmentAssets", b =>
                {
                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<int>("InvestmentPorfolioId")
                        .HasColumnType("int");

                    b.HasKey("AssetId", "InvestmentPorfolioId");

                    b.HasIndex("InvestmentPorfolioId");

                    b.ToTable("InvestmentAssets", (string)null);
                });

            modelBuilder.Entity("ItlaincenstmentApp.Core.Domain.Entities.InvestmentPorfolio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("Remove")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("InvestmentPorfolios", (string)null);
                });

            modelBuilder.Entity("ItlaincenstmentApp.Core.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("ItlaincenstmentApp.Core.Domain.Entities.Asset", b =>
                {
                    b.HasOne("ItlaincenstmentApp.Core.Domain.Entities.AssetType", "AssetType")
                        .WithMany("Assets")
                        .HasForeignKey("AssetTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssetType");
                });

            modelBuilder.Entity("ItlaincenstmentApp.Core.Domain.Entities.AssetHistory", b =>
                {
                    b.HasOne("ItlaincenstmentApp.Core.Domain.Entities.Asset", "Asset")
                        .WithMany("AssetHistories")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("ItlaincenstmentApp.Core.Domain.Entities.InvestmentAssets", b =>
                {
                    b.HasOne("ItlaincenstmentApp.Core.Domain.Entities.Asset", "Assets")
                        .WithMany("InvestmentAssets")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ItlaincenstmentApp.Core.Domain.Entities.InvestmentPorfolio", "InvestmentPorfolio")
                        .WithMany("InvestmentAssets")
                        .HasForeignKey("InvestmentPorfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assets");

                    b.Navigation("InvestmentPorfolio");
                });

            modelBuilder.Entity("ItlaincenstmentApp.Core.Domain.Entities.InvestmentPorfolio", b =>
                {
                    b.HasOne("ItlaincenstmentApp.Core.Domain.Entities.User", "User")
                        .WithMany("InvestmentPorfolios")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ItlaincenstmentApp.Core.Domain.Entities.Asset", b =>
                {
                    b.Navigation("AssetHistories");

                    b.Navigation("InvestmentAssets");
                });

            modelBuilder.Entity("ItlaincenstmentApp.Core.Domain.Entities.AssetType", b =>
                {
                    b.Navigation("Assets");
                });

            modelBuilder.Entity("ItlaincenstmentApp.Core.Domain.Entities.InvestmentPorfolio", b =>
                {
                    b.Navigation("InvestmentAssets");
                });

            modelBuilder.Entity("ItlaincenstmentApp.Core.Domain.Entities.User", b =>
                {
                    b.Navigation("InvestmentPorfolios");
                });
#pragma warning restore 612, 618
        }
    }
}
